version: '3'
services: 
  react-web-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4000:4000"
    volumes: 
      - /usr/app/react-web-app/node_modules
      - .:/usr/app/react-web-app
